FinalMeetupApp/config/routes.rb
FinalMeetupApp::Application.routes.draw do
  resources :memberships

  resources :sponsors

  resources :photos

  resources :venues

  resources :groups

  resources :events

  resources :users

end

FinalMeetupApp/app/models/membership.rb
class Membership < ActiveRecord::Base
  attr_accessible :groupid, :userid
end

FinalMeetupApp/app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController
  # GET /memberships
  # GET /memberships.json
  def index
    @memberships = Membership.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @memberships }
    end
  end

  # GET /memberships/1
  # GET /memberships/1.json
  def show
    @membership = Membership.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @membership }
    end
  end

  # GET /memberships/new
  # GET /memberships/new.json
  def new
    @membership = Membership.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @membership }
    end
  end

  # GET /memberships/1/edit
  def edit
    @membership = Membership.find(params[:id])
  end

  # POST /memberships
  # POST /memberships.json
  def create
    @membership = Membership.new(params[:membership])

    respond_to do |format|
      if @membership.save
        format.html { redirect_to @membership, notice: 'Membership was successfully created.' }
        format.json { render json: @membership, status: :created, location: @membership }
      else
        format.html { render action: "new" }
        format.json { render json: @membership.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /memberships/1
  # PUT /memberships/1.json
  def update
    @membership = Membership.find(params[:id])

    respond_to do |format|
      if @membership.update_attributes(params[:membership])
        format.html { redirect_to @membership, notice: 'Membership was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @membership.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /memberships/1
  # DELETE /memberships/1.json
  def destroy
    @membership = Membership.find(params[:id])
    @membership.destroy

    respond_to do |format|
      format.html { redirect_to memberships_url }
      format.json { head :no_content }
    end
  end
end

FinalMeetupApp/app/helpers/memberships_helper.rb
module MembershipsHelper
end

FinalMeetupApp/app/views/memberships/_form.html.erb
<%= form_for(@membership) do |f| %>
  <% if @membership.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@membership.errors.count, "error") %> prohibited this membership from being saved:</h2>

      <ul>
      <% @membership.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :userid %><br />
    <%= f.number_field :userid %>
  </div>
  <div class="field">
    <%= f.label :groupid %><br />
    <%= f.number_field :groupid %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

FinalMeetupApp/app/views/memberships/edit.html.erb
<h1>Editing membership</h1>

<%= render 'form' %>

<%= link_to 'Show', @membership %> |
<%= link_to 'Back', memberships_path %>

FinalMeetupApp/app/views/memberships/index.html.erb
<h1>Listing memberships</h1>

<table>
  <tr>
    <th>Userid</th>
    <th>Groupid</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @memberships.each do |membership| %>
  <tr>
    <td><%= membership.userid %></td>
    <td><%= membership.groupid %></td>
    <td><%= link_to 'Show', membership %></td>
    <td><%= link_to 'Edit', edit_membership_path(membership) %></td>
    <td><%= link_to 'Destroy', membership, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Membership', new_membership_path %>

FinalMeetupApp/app/views/memberships/new.html.erb
<h1>New membership</h1>

<%= render 'form' %>

<%= link_to 'Back', memberships_path %>

FinalMeetupApp/app/views/memberships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Userid:</b>
  <%= @membership.userid %>
</p>

<p>
  <b>Groupid:</b>
  <%= @membership.groupid %>
</p>


<%= link_to 'Edit', edit_membership_path(@membership) %> |
<%= link_to 'Back', memberships_path %>